#!/bin/sh

# Usage: build has_native

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1

add lib pkg/META                
add lib src/uutf.mli      
add lib src/uutf.cmi
add lib src/uutf.cmx
add lib src/uutf.cma
add lib src/uutf.a
add lib src/uutf.cmxa
add lib src/uutf.cmxs

add bin test/utftrip 

add doc README.md
add doc CHANGES.md
add doc test/examples.ml examples.ml

build
install uutf
